pipeline {
    agent any
    tools {nodejs 'Node19'}
    stages {
        stage('build') {
            steps {
                sh 'echo "Hello"'
                sh 'npm -v'
                sh 'npm cypress -v'
                sh 'pwd'
                sh 'ls -la'
                sh 'npx cypress run --spec cypress/e2e/MyFirstTest.cy.js'
            }
        }
    }
}